### ISSUE TITLE
Add ability to scale/zoom in and out

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/scancode-workbench#399]
### Description
It would useful to be able to zoom in and out (Like it is possible in a web browser).

**Comment by steven-esser** [comment]
@pombredanne I believe this is already present (Using ctrl+ and ctrl-): 
![Screenshot from 2019-10-08 12-25-55](https://user-images.githubusercontent.com/7485204/66414336-3183dd80-e9c7-11e9-8be5-561868f0131b.png)

**Comment by pombredanne** [comment]
Indeed... I had been using the older 3.1.0 ... Thank you!
