### ISSUE TITLE
Unidentified developer message for ScanCode-Workbench-macos-x64-3.1.1.tar.gz

### ISSUE THREAD

**Issue by DennisClark** [aboutcode-org/scancode-workbench#402]
Installed ScanCode-Workbench-macos-x64-3.1.1.tar.gz on Mac OS 10.14.5.   
When I double-click on the app name in the finder I get the cannot open because of unidentified developer message.  I can resolve that by holding down the Option key when I start the App, but it would be nice to fix this.  Screenshot of message attached. 

<img width="415" alt="Unidentified Developer SCWB 3 1 1" src="https://user-images.githubusercontent.com/4991620/67112647-93450400-f18c-11e9-9a7c-c172e2aa5df7.png">

**Comment by steven-esser** [comment]
@DennisClark We have decided to stop to paying apple $100 a year just for the ability to "sign" the application and have this message go away. 

There should be some small documentation for this in any case, as the process is not 100% clear.

**Comment by DennisClark** [comment]
@majurg   Thanks for the info.  Makes sense.
