### ISSUE TITLE
License Expression on a Conclusion not getting Uploaded

### ISSUE THREAD

**Issue by DennisClark** [aboutcode-org/scancode-workbench#403]
Using ScanCode-Workbench-macos-x64-3.1.1.tar.gz 
Loaded scan results glfw-3.3.tar.gz_scan.json 
Created Conclusion on glfw-3.3/deps/mingw and filled in most of the fields.  
The license(s) that I pick (both lgpl-2.1-plus and public-domain-disclaimer are offered) disappear from the License Expression field if I Save the Conclusion and then Edit it again. 
On the other hand, it appears that there is something (`lgpl-2.1-plus`) in the License Expression field when I look at the Conclusions view.

The Upload Conclusions process appears to work just fine, and it creates a new Product Component in DejaCode as requested, but there is nothing in the License Expression field in DejaCode. Hard to figure out exactly where the problem is happening. 

[glfw-3.3-test-files.zip](https://github.com/nexB/scancode-workbench/files/3745092/glfw-3.3-test-files.zip)

**Comment by DennisClark** [comment]
I also noticed that the "Feature" field, which has a value of `Support` in SCWB, is not getting populated on the uploaded Product Component.

**Comment by steven-esser** [comment]
I will take a look at this

**Comment by steven-esser** [comment]
#406 fixes the license_expression problems. Product components should now be created with a correct license_expression value. 

As far as the missing "Feature" field, this is missing on the DejaCode side with the product_component API. I have opened a ticket w.r.t. this here: https://github.com/nexB/dejacode/issues/978
