### ISSUE TITLE
Enable narrower display of Path column

### ISSUE THREAD

**Issue by johnmhoran** [aboutcode-org/scancode-workbench#410]
Working on Windows 10 with the latest development branch, using a built .exe.  Often I'm encountering a display of the Path column that is wider than any displayed Path values.  I'm also often seeing wide Path values displayed in full.  In both cases, this leaves precious little room to view any other columns.

I don't have a proposed solution at this point but will find time to examine the code and see if I can come up with an idea.

**Comment by johnmhoran** [comment]
I see paths, filenames, file_types etc. are sometimes abbreviated with ellipses.  You can see the entire string by mousing over, which is good, but the ellipses prevent copying the string for use elsewhere (e.g., other scan outputs, Google, DBs and the like).  Forced text-wrap (with fixed or max column widths) might be ugly but would display the entire value and permit copying.

**Comment by steven-esser** [comment]
This used to be the case until I did some work on #1. You can see the changes I made here: #375. Most of these modifications were done with .css changes, while the ellipsis function is handled via DataTables library. 

We do need some way to be able to copy these values (especially path and maybe a handful of others). I am open to any changes, even reverting to past behavior if thats required. The problem with word wrap is long paths make the cells very high in some cases, which make the data table really hard to scan.

**Comment by steven-esser** [comment]
Ideally, we would want fixed height and fixed width for all columns.

**Comment by johnmhoran** [comment]
It might also be worth exploring whether DataTables columns can be resized by the user.

**Comment by OmkarPh** [comment]
The latest version supports resizing all columns 
Can we close this issue?

**Comment by OmkarPh** [comment]
Closing this, as we're using new resizable columns in the Table view
