### ISSUE TITLE
Remove Upload Conclusions

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode-workbench#413]
We should remove Upload Conclusions (to DejaCode) from UI and the code. This functionality belongs in a ScanCode workflow outside the Workbench.
Also closing related Issues #338, #339, #391 and #392.

**Comment by steven-esser** [comment]
#420 Merged, closing this.

**Comment by mjherzog** [comment]
We also need to remove the Upload Conclusions button from the Conclusions View.

**Comment by steven-esser** [comment]
@mjherzog  This is fixed in the current develop branch. Changes will not be reflected until next release. 

I will leave this ticket open till then to avoid confusion.

**Comment by OmkarPh** [comment]
We don't support conclusions & it is already removed
