### ISSUE TITLE
Correct SourceForge download page

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode-workbench#421]
The SourceForge download page for ScanCode Workbench still says AboutCode Manager - https://sourceforge.net/projects/aboutcode-manager/. We have several v3.1.1 releases of ScanCode Workbench from January 2020.
Do we deprecate this download site or correct the information from AboutCode Manager to ScanCode Workbench.

**Comment by OmkarPh** [comment]
CC @pombredanne @mjherzog @AyanSinhaMahapatra

**Comment by mjherzog** [comment]
We should deprecate the SourceForge page. I do not know how to do that.

**Comment by pombredanne** [comment]
Done. This now redirects here!

**Comment by pombredanne** [comment]
Closing
