### ISSUE TITLE
Some Table View filters seem to use substrings rather than values

### ISSUE THREAD

**Issue by johnmhoran** [aboutcode-org/scancode-workbench#422]
Working on Windows 10 with ScanCode Workbench 3.1.1, I see that some (but not all) filters in the Table View display seem to apply the filter by using substrings rather than the values themselves.  For example:

File Size: `3` grabs `*3*`
File Type: `ASCII text` grabs `*ASCII text*`
License Expressions: `lgpl-2.1` grabs `*lgpl-2.1*`
License Key: `lgpl-2.1` grabs `*lgpl-2.1*`

A little over a year ago there was a similar issue that was resolved and perhaps could provide some guidance re how to resolve the behavior at issue here: [Filter by Language not working correctly](https://github.com/nexB/scancode-workbench/issues/320).

**Comment by chauhanparth210** [comment]
Hello @johnmhoran , I am Parth and I want to work on this issue.
Thank you.

**Comment by kkoehne** [comment]
Note that there's also a similar error in the 'Chart Summary View': https://github.com/nexB/scancode-workbench/issues/457

**Comment by OmkarPh** [comment]
This has been fixed as a part of refactoring, and is no longer an issue
