### ISSUE TITLE
Limit Table View search to selected columns

### ISSUE THREAD

**Issue by johnmhoran** [aboutcode-org/scancode-workbench#423]
The search feature in Table View (upper right-hand corner) currently searches all fields, whether or not the user has selected the relevant field/column for display.  As a result, at times it can be unclear why a particular row/resource is among the search results.

While reasonable minds can differ, it might be most useful to limit the search to fields/columns the user has selected for display.  In the best of all possible worlds, the user could choose (e.g., radio button) whether or not to limit the search to selected columns.

**Comment by vishnuiiit** [comment]
Sir, I think I can fix this issue, but I cannot find code can u help me?

**Comment by vishnuagbly** [comment]
Sir, I can fix this issue, I would really like to contact with you, to discuss more about issues and project.

**Comment by deadpool1999** [comment]
Hello , I am an aspirer for open source programming techniques.
May I please know where can I find the relevant files for this enhancement.

**Comment by chauhanparth210** [comment]
@deadpool1999 , @vishnuiiit  are you working on this issue ?
I want to work on this issue.

**Comment by vishnuagbly** [comment]
Sorry due to unseen circumstances I will not be able to work on it, I am
really sorry about it

**Comment by steven-esser** [comment]
@chauhanparth210 Go for it :)

**Comment by Aayush-hub** [comment]
@majurg Can I work on it?

**Comment by OmkarPh** [comment]
The latest implementation has search functionality working only for visible columns (which is the ideal scenario i think)
Do we still need this toggle for Searching across invisible columns too?
CC @pombredanne @mjherzog @AyanSinhaMahapatra

**Comment by mjherzog** [comment]
If can limit search to visible fields, we do not need a toggle.

**Comment by OmkarPh** [comment]
Closing this as the feature is already implemented and available in [v4.0.0](https://github.com/nexB/scancode-workbench/releases/tag/v4.0.0)
