### ISSUE TITLE
--include flage does not work and --ignore only allows you to ignore 1 file type

### ISSUE THREAD

**Issue by danzziy** [aboutcode-org/scancode-workbench#426]
### Description
The following are the errors i have encountered:
Error: no such option: --include
And -- ignore will simply not work if there is more than one value after it. 
scancode -clpeui -n 3 --ignore "*.js" 
scancode -clpeui -n 3 --ignore "*.js, *.cs"

### System configuration
I am using ubuntu and scancode is configured to use Python 2 the ScanCode version is 3.02

**Comment by steven-esser** [comment]
@danzziy You can specify multiple ignores in the following way: 
```
scancode -cleip --ignore "*.js" --ignore "*.css" --ignore "other-pattern"`
```

**Comment by steven-esser** [comment]
And `--include` is a valid flag on the latest `v3.1.1` release of scancode. The v3.0.2 release may not have this option. `--include` works the same way as `--ignore` afaik

**Comment by steven-esser** [comment]
Also note you opened this issue in [ScanCode Workbench](https://github.com/nexB/scancode-workbench/) instead of [scancode-toolkit](https://github.com/nexB/scancode-toolkit)

**Comment by danzziy** [comment]
Thank you for your help, sorry about posting on the wrong repository!

**Comment by danzziy** [comment]
scancode ` v3.1.1 ` needs pip3 to install that has solved the `--include` problem and you have solved the `--ignore` problem for me. Thank you!

**Comment by steven-esser** [comment]
Good to hear 👍
