### ISSUE TITLE
Update or remove copyright date in NOTICE file

### ISSUE THREAD

**Issue by johnmhoran** [aboutcode-org/scancode-workbench#435]
The [copyright date](https://github.com/nexB/scancode-workbench/blob/develop/NOTICE) (currently `2016`) needs to be updated or removed.  My inclination is to remove it.  @majurg  @mjherzog  -- what do you think?

BTW, looks like the mailing address needs to be updated as well.  Updated to . . . ?

**Comment by mjherzog** [comment]
Philippe has recommended that we drop copyright dates - presumably using our commit logs instead to establish timeline for code.
We do not yet have a new address - timing is unclear on that point for now.

**Comment by steven-esser** [comment]
#433 merged, closing this.
