### ISSUE TITLE
Hamburger Menu for Expand and Collapse of Side Menu Bar

### ISSUE THREAD

**Issue by nitin10s** [aboutcode-org/scancode-workbench#437]
### Description
The side menu bar should have an expand-collapse enabling button so that new users can use it to understand what all the options present mean. 

![Capture (1)](https://user-images.githubusercontent.com/16988558/79204527-523b5d00-7e5a-11ea-8cdb-cbd12355dd84.png)

**Comment by nitin10s** [comment]
Something like this:
![Group 9](https://user-images.githubusercontent.com/16988558/79205771-feca0e80-7e5b-11ea-88d4-302c815b6e33.png)

**Comment by steven-esser** [comment]
I like this initial idea. It may look good without the borders as well.

**Comment by Vishal-raj-1** [comment]
@majurg do you want this ?? @nitin10s Where should be that button (right side of sidebar)?

**Comment by nitin10s** [comment]
Which button @Vishal-raj-1 ?

**Comment by Vishal-raj-1** [comment]
I mean you want, we should have one toggle button. So that we can show full side bar or icons. So My Questions is where should be that toggle button.

**Comment by nitin10s** [comment]
If you see the proposed design, the toggle button is at the bottom.

**Comment by Vishal-raj-1** [comment]
> If you see the proposed design, the toggle button is at the bottom.

Thank you !! Looking forward to this issue

**Comment by steven-esser** [comment]
#480 merged, closing this. Thanks @Vishal-raj-1.
