### ISSUE TITLE
Doc: Some Icons in Side Menu Bar are unclear

### ISSUE THREAD

**Issue by nitin10s** [aboutcode-org/scancode-workbench#438]
### Description
I propose the following new icons: 
Welcome Page:
![home (1)](https://user-images.githubusercontent.com/16988558/79206626-3c7b6700-7e5d-11ea-8f33-9acab4815670.png)

File Info:
![folder](https://user-images.githubusercontent.com/16988558/79206632-3eddc100-7e5d-11ea-881b-effa295b886b.png)

**Comment by mjherzog** [comment]
It does probably make sense to use a Home icon for the Welcome page in the side menu, but the proposed Info icon does not seem any more "clear" than the current icon.

**Comment by nitin10s** [comment]
Ok, maybe, yes, the new one just had "i" written on a file. But I kind of agree it's not making it much clearer.

**Comment by steven-esser** [comment]
I am also open to using other icon packs, if they fall under some accessible OSS license.

**Comment by mjherzog** [comment]
In any case we need to use one set of icons for visual and code simplicity.

**Comment by OmkarPh** [comment]
Closing, as we have new set of icons in the updated workbench now
