### ISSUE TITLE
Doc: Confusion with the Help Sections

### ISSUE THREAD

**Issue by nitin10s** [aboutcode-org/scancode-workbench#440]
### Description
Currently, the ways to access documentation and Help are:
1. On the left menu bar
2. On the top main menu

This can be unnecessarily confusing and should be merged into one.

Also, there are some discrepancies like:
1. In Basics: The Link "ScanCode Workbench" opens Views, "Building" and "Platform Support" are not so important for users and could be included in the wiki itself and not presented in the application exclusively. We can discuss on this.
2. [On Welcome Page] The "How to run a scan with ScanCode Toolkit" button redirects to https://github.com/nexB/scancode-toolkit/wiki/How-To:-Run-a-scan, which basically mentions 3 different links of Documentation. Rather the button should directly link to https://scancode-toolkit.readthedocs.io/en/latest/tutorials/how_to_run_a_scan.html,

**Comment by steven-esser** [comment]
@nitin10s I think we are pretty open to suggestions here. I think at the very least we should have a link to the docs from the welcome page.

**Comment by OmkarPh** [comment]
Closing, as it was addressed recently in #602
