### ISSUE TITLE
Extra Unnecessary Margins in Columns [Table View]

### ISSUE THREAD

**Issue by nitin10s** [aboutcode-org/scancode-workbench#445]
### Description
![Workbench](https://user-images.githubusercontent.com/16988558/79641639-69f64680-81b6-11ea-93b0-8dee77ffcd57.PNG)

The spacing in this column is much more than required. This forces the other columns a very less space [Since the Path column is fixed]. How is the space to allotted decided? Proper margins should be specified for such columns.

Also, giving the functionality to adjust the size of the columns according to the user would significantly enhance the usability experience [Like in Excel]

**Comment by steven-esser** [comment]
@nitin10s I agree with this. Some of the problems stem from DataTables (and its plugins), but there is probably ways to get this working how we want it.

**Comment by Manan17** [comment]
Can I work on this issue?

**Comment by pombredanne** [comment]
@Manan17 sure thing: no need to ask permission! What would be your approach to this?

**Comment by OmkarPh** [comment]
Closing this as it is implemented in the latest workbench releases
The current implementation gives a reasonable initial width & allows users to resize
