### ISSUE TITLE
A way to report issues quickly from the application itself.

### ISSUE THREAD

**Issue by nitin10s** [aboutcode-org/scancode-workbench#446]
### Description
The application could add a way to report the issues they face there and then without any hassle by including an Issue Report Dialog Box [considering they have an internet connection]

Something like this [A Small Icon in the Lower Right Corner]:
![Web 1920 – 1](https://user-images.githubusercontent.com/16988558/79911854-b489f400-843e-11ea-8eb4-0d72bcd1191f.png)
![Web 1920 – 2](https://user-images.githubusercontent.com/16988558/79911860-b784e480-843e-11ea-914c-795de182d20a.png)

There might be an argument on the need for this feature since the users can already report the issue through Github. 
The reason this feature is very much needed is that users don't care to spend their valuable time to email/get to Github and open an issue. This feature makes it quick and easy to report small issues/errors there and then.

**Comment by steven-esser** [comment]
@nitin10s Where would these "Errors" be sent to?

**Comment by nitin10s** [comment]
[Considering the user has a working internet connection] we could create a new database for these or add these into some existing databases if any. Or a better solution, we could get these errors mailed to us directly without creating any new DB.

**Comment by pombredanne** [comment]
For this IMHO having a link that goes straight to GitHub with a prepopulated link would be plenty enough

**Comment by OmkarPh** [comment]
should i update this link only:
![image](https://user-images.githubusercontent.com/48476025/151296301-a66cc67e-972e-4e86-b6d1-ff30b3077276.png)

Or add a icon in bottom right like @nitin10s showed

**Comment by pombredanne** [comment]
IMHO for a start, something that would be like https://stackoverflow.com/questions/34146618/pre-populate-the-github-new-issue-form-using-the-querystring and https://docs.github.com/en/enterprise-server@3.1/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-url-query ....
The trick would be how to prepopulate this nicely for this to be useful.

**Comment by OmkarPh** [comment]
Hi @pombredanne 
before going ahead with this, it think this PR #501 should be dealt with
can you merge / close / propose any changes in this PR

**Comment by pombredanne** [comment]
@OmkarPh  why would an issue template be required and in the way of this issue? Can you explain?

**Comment by OmkarPh** [comment]
I'll give an example.
If you click on New issue btn on this repo: https://github.com/layer5io/layer5/issues
You get a list of templates to choose from
For every issue template, there's a defined URL, eg:
https://github.com/layer5io/layer5/issues/new?template=feature_request.md
https://github.com/layer5io/layer5/issues/new?template=bug_report.md

For workbench, if we want to have similar issue templates, we can provide 2 3 types of links based on what user wants (bug/feature/review, etc) and the description will be prefilled with corresponding template

**Comment by pombredanne** [comment]
@OmkarPh OK, I understand now... for a start this feels a bit to complicated to me, let's start with something simple

**Comment by OmkarPh** [comment]
> @OmkarPh OK, I understand now... for a start this feels a bit to complicated to me, let's start with something simple
 
@pombredanne
https://github.com/nexB/scancode-workbench/issues/new
current default template should do the work then
