### ISSUE TITLE
Redesigning Welcome Page

### ISSUE THREAD

**Issue by nitin10s** [aboutcode-org/scancode-workbench#447]
### Description
Please leave a brief description of the bug or feature request:
Not sure where to post my designs, so I am posting it both on Gitter and here. Please review and suggest improvements, if any.
![Wokbench-Welcome](https://user-images.githubusercontent.com/16988558/80581132-58206900-8a2a-11ea-871a-ae4d9103a181.png)

**Comment by steven-esser** [comment]
@nitin10s I like this iteration of the welcome page a lot. 

One thing to make sure is that the documentation links go to our RTD page: https://scancode-workbench.readthedocs.io/en/develop/

As long as you have that, I would be happy to have this.

**Comment by nitin10s** [comment]
Indeed. Also if you see, I have reduced the number of different links that were previously present on the welcome screen. Did this to simplify things for the user with only the most relevant links to display. For further information, he could reach to the Help section.

Let me know if these links aren't apt or any other more links should be added to the welcome screen.

**Comment by Ayushsunny** [comment]
I wanna work on this issue.

**Comment by Vishal-raj-1** [comment]
I am looking forward to this issue !!
