### ISSUE TITLE
License, Package, File Info Redesigned

### ISSUE THREAD

**Issue by nitin10s** [aboutcode-org/scancode-workbench#449]
### Description
Please leave a brief description of the bug or feature request:
1. Kept the pages almost similar to the current ones following a particular design theme. 
![File Info Dashboard](https://user-images.githubusercontent.com/16988558/80721997-84b4ad80-8b1c-11ea-9d8c-2dac4f87578d.png)
![License Info Dashboard](https://user-images.githubusercontent.com/16988558/80722004-87af9e00-8b1c-11ea-9742-d5304326e268.png)
![Package Info Dashboard](https://user-images.githubusercontent.com/16988558/80722019-89796180-8b1c-11ea-8ec5-65b05d489012.png)
Reviews and suggestions are welcomed :)

**Comment by steven-esser** [comment]
@nitin10s On the file info dashboard, we want to move toward adding some table-like elements here.

See: https://github.com/nexB/scancode-workbench/issues/381 for more suggestions as to what we want to do with these dashboards.

**Comment by nitin10s** [comment]
Okay will look into this.

**Comment by Aayush-hub** [comment]
@majurg Can I work on redesigning issues?

**Comment by OmkarPh** [comment]
We have new design & updates in Scancode workbench
Closing this
