### ISSUE TITLE
Improve Conclusions Help/Documentation

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode-workbench#452]
This Issue is an enhancement for the Edit Conclusion modal window to to make it more clear which fields are usually based on Scan data versus Conclusion-only data.

1. Scan-based fields are:
- License Expression
- Owner
- Copyright
- Programming Language
- Homepage URL
- Download URL
- License URL
- Notice URL

Although you can enter data into these fields directly, a primary feature for these fields is to use/choose data from the Scan when it is available. If none is available you get the message "No results found", but it is not easy to see that now and the mouse-over Help text does not explain the relationship of the data to Scan data.

2. Conclusion-only (entry only) fields are:
- Status (LOV)
- Name
- Version
- Modified
- Deployed 
- Code Type 
- Notes
- Feature
- Purpose

A first step could be to update the Help text - e.g. for License Expression where:
Current text is: "The license expression that applies to a conclusion"
New text could be: "The license expression that applies to this conclusion. SCWB will present possible values from the Scan"

**Comment by kopal960** [comment]
@mjherzog Can I work on this issue ?

**Comment by Ayushsunny** [comment]
I wanna work on this issue.

**Comment by steven-esser** [comment]
@Ayushsunny: Feel free, all open issues are free to work on.

**Comment by Aayush-hub** [comment]
@majurg Is this issue still open for work??

**Comment by mjherzog** [comment]
Closing because we are deprecating Conclusions in SCWB in favor of building a more robust feature in SCIO.
