### ISSUE TITLE
Correct column names to singular

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode-workbench#453]
Our standard is to use singular column names even though a field may contain multiple values. 
The following column names from SCWB v3.1.1 should be reset to singular:
- Copyright Statements
- Copyright Holders
- Copyright Authors
- License Expressions
- Scan Errors

**Comment by devil-cyber** [comment]
Hey @mjherzog can you please explain this issue to me, I would like to work on this issue ?

**Comment by NinaPacifier** [comment]
Hey @mjherzog, Can I work on this issue??

**Comment by steven-esser** [comment]
@devil-cyber The issue description has a decent explanation of the problem. Is there a specific question you had?

@NinaPacifier Sure

**Comment by pranav1698** [comment]
@NinaPacifier are you working on this?
I would like to work on this one

**Comment by steven-esser** [comment]
@pranav1698 Feel free to tackle this.

**Comment by pranav1698** [comment]
@majurg sure

**Comment by pranav1698** [comment]
@majurg @mjherzog please review #474
