### ISSUE TITLE
In the package view, present rows for package and not for files as major

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/scancode-workbench#458]
### Description
When I look at packages, I would expect to see a list of packages only (and possibly some way to drill down by files). Instead we have a list of files with aggregated package data. This possibly confusing when there are more than one package at a given directory of file level

**Comment by sohamsshah** [comment]
Hey! I just came across this project and found quite interesting! Can you elaborate this issue? I would love to contribute to this project😁

**Comment by steven-esser** [comment]
The gist of this feature request is to have some sort of view that only displays `packages` data after importing a scan. 

This info is in the sqlite file after scan importing, so the majority of the work here would be to create a view for only this package data.

**Comment by kshitij86** [comment]
@majurg I would like to create the view for the `packages` data. Can I get assigned to implement this enhancement?

**Comment by pranav1698** [comment]
@pombredanne @majurg isn't this feature already present in the application
After importing the json, I can see the parent package and also drill down to other packages and files present in the imported package
![Screenshot from 2021-01-07 01-46-22](https://user-images.githubusercontent.com/34754265/103815966-2d42e600-508a-11eb-9227-aee9c6b3753e.png)

**Comment by steven-esser** [comment]
@pranav1698 The feature to display package data has always been there. What is missing is a view that shows ONLY package data, instead of just displaying package data next to non-package items, like random source files etc.

**Comment by OmkarPh** [comment]
Closing, as we already have Package Explorer section in workbench v4.x 
Ref - https://scancode-workbench.readthedocs.io/en/develop/ui-reference/package-explorer.html#package-explorer
