### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by 112002** [aboutcode-org/scancode-workbench#459]
### Description
Please leave a brief discription of the bug or feature request:
* if reporting a bug, tell us how to reproduce the issue.
* Check the Develop Console tab and copy any error text there might be: https://scancode-workbench.readthedocs.io/en/develop/basics/check_for_errors_in_the_developer_tools.html

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? (Windows/MacOS/Linux)
* What version of scancode-workbench are you running on?
* What version of scancode-toolkit was used to generate the scan file?

**Comment by pombredanne** [comment]
There is no issue in this ticket. So I am closing for now.
