### ISSUE TITLE
Build configuration error : No output was received(Job errored)

### ISSUE THREAD

**Issue by kopal960** [aboutcode-org/scancode-workbench#471]
#### Bug report
Build for the scancode-workbench at travis-ci.org for #470 is failing.
Following is the error log : 
```
$ openssl aes-256-cbc -K $encrypted_906d16ae5679_key -iv $encrypted_906d16ae5679_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
iv undefined
after_success.2
0.01s$ chmod 600 /tmp/deploy_rsa
$ scp -i /tmp/deploy_rsa dist/ScanCode*.tar.gz aboutcode-rel@web.sourceforge.net:/home/frs/project/aboutcode-manager/builds/
Warning: Permanently added the RSA host key for IP address '216.105.38.21' to the list of known hosts.
Load key "/tmp/deploy_rsa": invalid format
Password: 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```
Here are the complete build logs : https://travis-ci.org/github/nexB/scancode-workbench/builds/751369530

### System configuration
The changes in #470 were made using windows operating system.

**Comment by steven-esser** [comment]
@kopal960 Thanks for this. 

If I recall, this is related to a broken Sourceforge upload location for windows builds.

**Comment by OmkarPh** [comment]
We've a new refactored ScanCode workbench, It is released via Github Actions and builds work fine now
Closing, as the mentioned issue is not relevant anymore
