### ISSUE TITLE
Double scroll bar on clicking the Hide all button in ScanCode Data Table

### ISSUE THREAD

**Issue by pranav1698** [aboutcode-org/scancode-workbench#473]
### Description
**Bug Report**
In the ScanCode Data Table, when I click the **Hide All** button, the application shows double scrollbar at the bottom of the page. I am attaching a screenshot for your reference
![Screenshot from 2021-01-07 03-31-24](https://user-images.githubusercontent.com/34754265/103823825-d55fab80-5098-11eb-8880-187899595af1.png)

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? (Linux)
* What version of scancode-workbench are you running on? (v3.1.1)
* What version of scancode-toolkit was used to generate the scan file?(Sample json file)

**Comment by Dhruvitt** [comment]
Hi can i get start on trying to solve the issue also can you give me a head start.
