### ISSUE TITLE
Link need to be added in Report Issue section

### ISSUE THREAD

**Issue by s4-2** [aboutcode-org/scancode-workbench#487]
### Description
**Feature**

- The [Report Issue](https://scancode-workbench.readthedocs.io/en/develop/contribute/reporting-issues.html) of scancode-workbench [Documentaion](https://scancode-workbench.readthedocs.io/en/develop/) we must include a link which take the docs reader directly to the New Issue where they can report there issues.

**Comment by Pushpit07** [comment]
I'll take up this and add the link

**Comment by s4-2** [comment]
Okay, Thank you @Pushpit07 :-)

**Comment by steven-esser** [comment]
This was done by #488. Thanks @Pushpit07
