### ISSUE TITLE
Getting an error!

### ISSUE THREAD

**Issue by cnu1812** [aboutcode-org/scancode-workbench#491]
![Screenshot 2021-03-27 134548](https://user-images.githubusercontent.com/75531528/112714942-02d32d00-8f03-11eb-8f5d-a518a8cf1aba.png)
### Description
Please leave a brief discription of the bug or feature request:
While running the main.js in compiler their is an error showing module not found!
* if reporting a bug, tell us how to reproduce the issue.
* Check the Develop Console tab and copy any error text there might be: https://scancode-workbench.readthedocs.io/en/develop/basics/check_for_errors_in_the_developer_tools.html

### System configuration
For bug reports, it really helps us to know:
* Windows (Windows/MacOS/Linux)
* Version is    ###3.1.1
* What version of scancode-toolkit was used to generate the scan file?

**Comment by Dinesh101041** [comment]
hi bro why are you using main.js start file

**Comment by steven-esser** [comment]
@cnu1812 You are running `scancode-workbench` the wrong way. Please follow the directions in the README: https://github.com/nexB/scancode-workbench#building
