### ISSUE TITLE
Must restart the workbench in order reimport the same json file

### ISSUE THREAD

**Issue by poti1** [aboutcode-org/scancode-workbench#494]
### Description

I must restart the workbench in order reimport the same json file

Steps to reproduce:
1. Import a json file into the workbench
2. Select the sqlite file.
3. Click Save
4. Update the json file to include the policy label (using scancode --license-policy FILE)

![image](https://user-images.githubusercontent.com/75398062/114005725-1e71f800-9860-11eb-9b3e-59b92db52a19.png)

### System configuration
Windows 10
scancode-workbench 3.1.1
scancode-toolkit 21.3.31
Python 3.6.2

**Comment by steven-esser** [comment]
@poti1 This is expected behavior for the time being. Once you import a JSON file, The corresponding sqlite file gets created: 
```
scan.json ==> scan.sqlite
```

If you were to then modify `scan.json`, you would need to re-import this to see the changes. `scancode-workbench` does not dynamically load data from scan files.
