### ISSUE TITLE
Unable to export from workbench

### ISSUE THREAD

**Issue by poti1** [aboutcode-org/scancode-workbench#495]
### Description
I want to export my results, but it does not seem to work.

### System configuration
Windows 10
scancode-workbench 3.1.1
scancode-toolkit 21.3.31
Python 3.6.2

**Comment by pratik0316** [comment]
@poti1 please post the error logs too if it's present

**Comment by steven-esser** [comment]
@poti1 Can you give more context here? Are you trying to export a results sqlite file OR some user-created set of conclusions?

**Comment by FrySlim** [comment]
I got the same issue:

1. npm start => SCWB starts
2. "Import ScanCode JSON", selecting a "json-lines" file 'sclicense-output.json' from scancode toolkit 30.1.0 output
3. "Saving a "sclicense-output.sqlite" SQLite Database file in the same directory
4. Doing my conclusion edits, when I am done it looks like this:
![image](https://user-images.githubusercontent.com/42751342/155585251-0a72617b-7ea1-4c50-9120-d0f77c34d372.png)
5. "File">"Export Conclusions JSON File" and trying to save as "sclicense-conclusion.json" in the same directory.
**=> no json file is saved.**
_(Windows Server 2016, npm 8.3.1, node 16.14.0, python 3.9.10, pip 22.0.3, SCWB 3.11)_

Maybe it has something to do with the sequelizejs deprecated message in the command box:
```
E:\sctk\scancode-workbench>npm start

> scancode-workbench@3.1.1 start
> electron main.js
(node:11616) Electron: Loading non-context-aware native module in renderer: '\\?\E:\sctk\scancode-workbench\node_modules\sqlite3\lib\binding\electron-v13.0-win32-x64\node_sqlite3.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(Use `electron --trace-warnings ...` to show where the warning was created)
Thu, 24 Feb 2022 18:20:28 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules\sequelize\lib\sequelize.js:245:13
(node:11616) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Thu, 24 Feb 2022 18:25:12 GMT sequelize deprecated Model.findById has been deprecated, please use Model.findByPk instead at node_modules\sequelize\lib\model.js:4208:9
```

I have no other log file seen laying around.

Regards
FrySlim

**Comment by FrySlim** [comment]
Neither with develop branch nor with master branch I got the "npm start" to work. Electron GUI starts but the Open/Save file dialogues  do not appear.

But, the ready built 'dist' release Binaries with ScanCode-Workbench.exe works :-)

**Comment by OmkarPh** [comment]
I think we're no longer supporting conclusions as discussed here #512

**Comment by mjherzog** [comment]
The Conclusions feature was deprecated for v4. We plan to eventually add this functionality in SCIO instead where we already have a shared database.
