### ISSUE TITLE
JSON file link broken in readme

### ISSUE THREAD

**Issue by Aayush-hub** [aboutcode-org/scancode-workbench#498]
## How to reproduce the issue.
* Scroll to Readme and click Import a JSON file and see the error.

**Comment by Aayush-hub** [comment]
@majurg @johnmhoran Can you please share the right link for importing json file for documentation updation?

**Comment by pratik0316** [comment]
@Aayush-hub if possible  u can create one yourself

**Comment by Aayush-hub** [comment]
@Pratikrocks Can I replace the json file link by one of the sample json file in the project??

**Comment by pratik0316** [comment]
@Aayush-hub I haven't checked that, if that's relevant you may replace with it 👍
