### ISSUE TITLE
Support for Python3

### ISSUE THREAD

**Issue by Aayush-hub** [aboutcode-org/scancode-workbench#502]
### Description
Please leave a brief discription of the bug or feature request: Python 2.7 is depreciated , so we can add support for python version 3 ,as scancode-toolkit is also updated to that version.
* if reporting a bug, tell us how to reproduce the issue. `run python build.py`
* Check the Develop Console tab and copy any error text there might be: https://scancode-workbench.readthedocs.io/en/develop/basics/check_for_errors_in_the_developer_tools.html

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? (Windows)
* What version of scancode-workbench are you running on? Latest

**Comment by OmkarPh** [comment]
Can I try this out

**Comment by pombredanne** [comment]
@OmkarPh Please!
