### ISSUE TITLE
Error updating dependency versions

### ISSUE THREAD

**Issue by OmkarPh** [aboutcode-org/scancode-workbench#508]
### Description
I'm trying to update dependencies of the project. My forked changes: 
[https://github.com/OmkarPh/scancode-workbench/tree/fix/oldDependencies](https://github.com/OmkarPh/scancode-workbench/tree/fix/oldDependencies)

I did npm update & npm install. Also did the electron-rebuild to ensure latest native builds for sqlite3
But am facing the following err:
![image](https://user-images.githubusercontent.com/48476025/148678908-1479ae88-cd68-43a0-9e8b-a57e30b41f47.png)

Err stack trace:
Uncaught Error: Loading non-context-aware native module in renderer: '/Users/omkar/projects/scancode-workbench/node_modules/sqlite3/lib/binding/electron-v16.0-darwin-arm64/node_sqlite3.node'. See https://github.com/electron/electron/issues/18397.
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5)
    at Module.load (node:internal/modules/cjs/loader:988)
    at Module._load (node:internal/modules/cjs/loader:829)
    at Function.c._load (node:electron/js2c/asar_bundle:5)
    at Function.o._load (node:electron/js2c/renderer_init:33)
    at Module.require (node:internal/modules/cjs/loader:1012)
    at require (node:internal/modules/cjs/helpers:94)
    at Object.<anonymous> (/Users/omkar/projects/scancode-workbench/node_modules/sqlite3/lib/sqlite3-binding.js:4)

### System configuration
* Macbook air M1, MacOS Monterey 12.1
* Forked from latest develop branch

**Comment by OmkarPh** [comment]
@pombredanne ^^

**Comment by OmkarPh** [comment]
I've updated the dependencies to following versions:

```
  "devDependencies": {
    "asar": "^3.1.0",
    "chai": "^4.3.4",
    "chai-subset": "^1.6.0",
    "electron": "^16.0.6",
    "electron-packager": "^15.4.0",
    "electron-rebuild": "^3.2.5",
    "eslint": "^8.6.0",
    "globby": "^12.0.2",
    "grunt": "^1.4.1",
    "jquery": "^3.6.0",
    "jsdom": "^19.0.0",
    "mocha": "^9.1.3",
    "nodemon": "^2.0.15",
    "sinon": "^12.0.1"
  },
  "dependencies": {
    "@electron/remote": "^2.0.1",
    "JSONStream": "^1.3.5",
    "packageurl-js": "^0.0.5",
    "sequelize": "6.12.5",
    "sequelize-cli": "6.3.0",
    "sqlite3": "^4.2.0"
  }
```

**Comment by pombredanne** [comment]
@OmkarPh thanks!
on gitter, you mentioned this:

> The err as well as most of StackOverflow answers point to this discussion:
electron/electron#18397

> One way is to stick with electron v13, but we can't stick to a single version forever.
> Please suggest any other way :(


Which one is the problematic native module?

Note also that the v13 is the current official released and maintained version, so sticking to a single version forever is not yet a problem... and I would surmise it will be solved somehow soon.

**Comment by OmkarPh** [comment]
> Which one is the problematic native module?

It was sqlite3 I guess.

> Note also that the v13 is the current official released and maintained version, so sticking to a single version forever is not yet a problem... and I would surmise it will be solved somehow soon.

Got it 👍
