### ISSUE TITLE
Remove editable conclusions features

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/scancode-workbench#512]
### Description
We should remove the ability to enter conclusions. This should be instead a new design that would be best based on ScanCode.io and automation.

**Comment by OmkarPh** [comment]
hi @pombredanne 
what is the goal here?

remove this entire screen?
![image](https://user-images.githubusercontent.com/48476025/164260489-fde6d064-5c7c-47b5-a7df-7ef18176bf90.png)

**Comment by mjherzog** [comment]
The goal is to remove this feature and replace it in the future with a different approach. Part of the goal is to simplify and refactor the code.

**Comment by OmkarPh** [comment]
so, should I open a PR with this page removed completely?

**Comment by pombredanne** [comment]
@OmkarPh yes and also remove the corresponding models and related code.
