### ISSUE TITLE
Refactor: Shift to Typescript + React

### ISSUE THREAD

**Issue by OmkarPh** [aboutcode-org/scancode-workbench#518]
### Description

Currently workbench is using vanilla js in electron. Shifting to typescript and react can improve development experience in many ways

### Why Typescript
* Reliable and predictable code
* More efficient auto completes, hence better development experience

### Why react
* Modularize workbench
   - Currently workbench has some large js files
      Example, [renderer.js](https://github.com/nexB/scancode-workbench/blob/develop/assets/app/js/renderer.js)  (560+ lines)
      This includes a giant `$(document).ready` callback code to update User interface
        
      Using react will help separating UI for each element in their own components, thereby easy to understand and work on specific part of project

 * Routing can be used to represent various sections of the workbench
 *  Context API can be used to share imported info across the created components.
    For example, if we go to the File info dashboard without importing any data, we see loaders (which will keep loading forever until we import any data)
    
    <img width="870" alt="Screenshot 2022-04-16 at 12 27 23 PM" src="https://user-images.githubusercontent.com/48476025/163665335-29c4ecfd-e326-41a6-9cca-0854ae396290.png">

    We can store imported data status in a context and react will automatically update the UI accordingly
    For example, we can have an imported enum with status `UN_IMPORTED`, `IMPORTING`, `IMPORTED` and each component can fetch update itself based on this status
    
    Moreover, we can restrict users from accessing specific routes (Sections) altogether.

 - There are variety of React component libraries we can use to improve user experience of our app without much effort
   
 - Lastly, react being a popular library, more contributors will be attracted and contribute to workbench as the friction to begin will decrease significantly

**Comment by OmkarPh** [comment]
@pombredanne @mjherzog Your thoughts on this

**Comment by pombredanne** [comment]
@OmkarPh this is looking great!

**Comment by AyanSinhaMahapatra** [comment]
@OmkarPh Thanks +++

This is now completed with https://github.com/nexB/scancode-workbench/releases/tag/v4.0.0rc2 and https://github.com/nexB/scancode-workbench/tree/v4.0-react-typescript, closing this!
