### ISSUE TITLE
Export JSON doesn't work

### ISSUE THREAD

**Issue by OmkarPh** [aboutcode-org/scancode-workbench#522]
Note - This occurs in develop branch, not the released version.

### Description
* Click on `Export JSON file` from menu item `file` or Use shortcut `cmd+e` / `ctrl+e`
* Choose path to export json to, export
* This gives following error in console:
![image](https://user-images.githubusercontent.com/48476025/165585721-e602076b-c430-4e03-bb30-698e55fa68c8.png)

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? Macos monterey
* What version of scancode-workbench are you running on? develop branch
* What version of scancode-toolkit was used to generate the scan file? samples directory examples

**Comment by OmkarPh** [comment]
@pombredanne 
Do you know the cause for this?

**Comment by AyanSinhaMahapatra** [comment]
@OmkarPh this is because of output format mismatch between scancode-toolkit and scancode-workbench, i.e. the scancodo-workbench last release supports a much older scancode-toolkit version (there used to be a header `scancode_notice` which was replaced later). 

Apart from this exact failure there are a lot of other major data format mismatches too, this need to be fixed to support later scancode-toolkit versions.

**Comment by OmkarPh** [comment]
ohh, got it

can you send me link or actual sample files exported from latest scancode-toolkit

I'm not familiar with scancode-toolkit, but i think this should be the latest format : https://scancodeio.readthedocs.io/en/latest/output-files.html#understanding-output-files

**Comment by AyanSinhaMahapatra** [comment]
Check out https://github.com/nexB/scancode-toolkit-reference-scans/tree/d03c03a2dacd83c89f79241a20633fde9d1caf06/docs/source/outputs and https://github.com/nexB/scancode-toolkit/blob/v30.1.0/tests/scancode/data/rpm/fping-2.4-0.b2.rhfc1.dag.i386.rpm.expected.json for some examples. These are for scancode v30.1.0 btw.

Btw, the output data is evolving fast and you should see a lot of changes in the latest develop, see https://github.com/nexB/scancode-toolkit/blob/develop/tests/scancode/data/rpm/fping-2.4-0.b2.rhfc1.dag.i386.rpm.expected.json for a comparision.

**Comment by mjherzog** [comment]
There is no current need for an Export function in SCWB v4 because there is no data created in SCWB with the deprecation of Conclusions.
