### ISSUE TITLE
Selecting values in filter dropdown sometimes results in a no-matching-records message

### ISSUE THREAD

**Issue by johnmhoran** [aboutcode-org/scancode-workbench#523]
During a recent project, I noticed that after properly activating the column filters, from time to time there were values displayed in a filter that, when selected, resulted in a message that no such records exist (`No matching records found`).  This occurred in SCWB 3.1.1 on a Windows 10 laptop.

**Comment by OmkarPh** [comment]
hey @johnmhoran closing this for now.
Feel free to open an issue if you face this problem again
