### ISSUE TITLE
Support latest scancode toolkit

### ISSUE THREAD

**Issue by OmkarPh** [aboutcode-org/scancode-workbench#525]
### Description
* Workbench doesn't support json files from latest scancode toolkit due to lack of updates
* Sqlite can be updated to support latest output json documented here: https://scancodeio.readthedocs.io/en/latest/output-files.html
* Format mismatch causes errors like this: https://github.com/nexB/scancode-workbench/issues/522

**Comment by OmkarPh** [comment]
Update - WIP in branch [v4.0-react-typescript](https://github.com/OmkarPh/scancode-workbench/tree/v4.0-react-typescript)

**Comment by martin-langhoff** [comment]
In my testing, latest release of ScanCode Workbench v3.1.1 works well with output from ScanCode Toolkit v30.1.0, but not with output from v31.x.y series. 

When used with output from v31.x.y series, it just does not "see" or report any licenses or copyrights. Visualization only tracks directories/files, but no properties 'discovered' for them. The data is in the JSON file, but is not parsed by Workbench.

**Comment by pombredanne** [comment]
@martin-langhoff This is correct, we have an updated branch that is pending last mile review before merging. Can you give a shot to https://github.com/nexB/scancode-workbench/pull/532 (only if you feel comfy with building from sources)

**Comment by martin-langhoff** [comment]
@pombredanne thanks for the update. I am more than happy to build from source _but_ current master is pretty broken for me when building on Mac OS. node-gyp spews all over. I'll try on the PR branch you are suggesting and report on the PR itself.

**Comment by martin-langhoff** [comment]
Testing your PR 
- branch builds on my Mac OS 12.6.1 with Node from Brew (whereas `develop` is broken on node-gyp)
- tested with an input report.json built with latest 'develop' commit in scancode-toolkit, the test run was over the git source code repo
- Import worked well
- In dashboard, Copyright Holders looks a bit odd (screencap below)
- License info dashboard had no data, this is incorrect (JSON file has license data)

![image](https://user-images.githubusercontent.com/5116932/205177178-62c0f15a-036b-47d7-a519-726252995efd.png)

**Comment by martin-langhoff** [comment]
(posted same message on #532 )

**Comment by pombredanne** [comment]
@martin-langhoff Thank you ++ for testing.
The issue is that we are in the process to update the data format for ScanCode licenses in the develop branch.
@AyanSinhaMahapatra ping

**Comment by AyanSinhaMahapatra** [comment]
This is now completed with https://github.com/nexB/scancode-workbench/releases/tag/v4.0.0rc2 supporting the latest scancode-toolkit v32.x output format, code is at https://github.com/nexB/scancode-workbench/tree/v4.0-react-typescript

@martin-langhoff please do test this out :rocket:
