### ISSUE TITLE
Prototype for a new Navbar in React+Typescript

### ISSUE THREAD

**Issue by OmkarPh** [aboutcode-org/scancode-workbench#528]
### Description
I've started prototyping the react+typescript version of the workbench, but since it has a completely different config, I've created a personal repository to share it for now. You can see the code here: https://github.com/OmkarPh/workbench-prototype

You can have a quick look here:
https://drive.google.com/file/d/1T-l55cx6Av28i1wrGNzKhwN3ojZ7xPXS/view?usp=sharing
https://drive.google.com/file/d/1oS_fEzLFJqsUwItaoYnI0Yi8s5jDSmG2/view?usp=sharing

Here's a screenshot of Navbar2
![image](https://user-images.githubusercontent.com/48476025/172207874-f7bd7a5b-005c-4d6e-908a-77d5d032de36.png)

You can try the navbar variants by choosing `<Navbar />` or `<Navbar2 />` in [App.tsx](https://github.com/OmkarPh/workbench-prototype/blob/48fe3d9efb63ff1f08b91408779fe14783a38368/src/App.tsx#L25)

Also, you can turn the 'expand on hover' on or off by the `const expandOnHover = true;` boolean in Navbar component of both the variants

**Comment by steven-esser** [comment]
This look good, design wise. Do you have an idea of what you want to use for the table and tree view? I seem to recall potential libraries in the gitter chat, but I could be wrong. Just wondering BTW. It would be very nice if the react libraries improve performance in the application, but who knows.

**Comment by OmkarPh** [comment]
> This look good, design wise. Do you have an idea of what you want to use for the table and tree view? I seem to recall potential libraries in the gitter chat, but I could be wrong. Just wondering BTW. It would be very nice if the react libraries improve performance in the application, but who knows.

yes, here are some good libraries for table:
https://reactdatagrid.io/demo
https://material-table.com/#/
https://www.npmjs.com/package/mui-datatables

I haven't yet searched about tree view, will do that soon

**Comment by OmkarPh** [comment]
Feedbacks:

@chinyeungli : the sidebar is cool and I like it very much too.. for me, I like "click" to expand more than hover to expand, but maybe that's just me.

**Comment by OmkarPh** [comment]
We can also think about providing a toggle to the user, whether to auto collapse or not.

**Comment by AyanSinhaMahapatra** [comment]
This is now completed with This is now completed with https://github.com/nexB/scancode-workbench/releases/tag/v4.0.0rc2 , and the new navbar looks and feels great to use! Thanks+++ @OmkarPh
