### ISSUE TITLE
Curations and exporting curated results

### ISSUE THREAD

**Issue by LeChasseur** [aboutcode-org/scancode-workbench#538]
Scancode Workbench allows you to check and review scan results. Frequently, there is a need to correct "false positives" and re-export the curated results. Exporting subsets after filtering would also be helpful. 

### System configuration

* Linux
* Workbench 3.1.1
* ScanCode version: 31.0.0rc2

**Comment by mjherzog** [comment]
We have deprecated the Conclusions feature for SCWB v4 because it was too limited as-is in v3 for real world use. We are revisiting the model for curation across the AboutCode projects.
