### ISSUE TITLE
Improve design for history section (Good to have)

### ISSUE THREAD

**Issue by OmkarPh** [aboutcode-org/scancode-workbench#540]
One suggestion
![image](https://user-images.githubusercontent.com/48476025/194912511-b81c93b0-b77b-4a01-96c2-d43c2c0f9cb6.png)

**Comment by roopeshsn** [comment]
I would like to work on this.

**Comment by vishant007** [comment]
Hey, I want to contribute on this issue through GSOC-2023,is this issue still open?

**Comment by AyanSinhaMahapatra** [comment]
@vishant007 scancode-workbench is not part of GSoC 2023, see https://github.com/nexB/aboutcode/wiki/GSOC-2023#aboutcode-projects-are, but if you mean you want to contribute to this issue as a part of pre-gsoc contributions, you are welcome to do so (but keep in mind contributions to issues in the project you're actually applying for counts more).

**Comment by AyanSinhaMahapatra** [comment]
We have an updated design for the history section at  https://github.com/nexB/scancode-workbench/releases/tag/v4.0.0rc2 by @OmkarPh 

![workbench-history](https://user-images.githubusercontent.com/25746274/232040903-bfc54a79-25e4-4110-a7c5-b8a7cd0f3f78.png)

@OmkarPh feel free to close this if this is completed, Thanks++

**Comment by OmkarPh** [comment]
yep
