### ISSUE TITLE
Content: Title & Link for No chart fallback

### ISSUE THREAD

**Issue by OmkarPh** [aboutcode-org/scancode-workbench#541]
### Description
What should be the ideal title and links for each of the following chart's fallback?

Here's what is currently in place
* File Info dashboard
  * Programming languages
     Use --info CLI option for programming languages
     https://scancode-toolkit.readthedocs.io/en/stable/cli-reference/basic-options.html#all-basic-scan-options
  * File types
     Use --info CLI option for file types
     https://scancode-toolkit.readthedocs.io/en/stable/cli-reference/basic-options.html#all-basic-scan-options
  * Copyright holders
     Use --copyright CLI option for copyright data
     https://scancode-toolkit.readthedocs.io/en/stable/cli-reference/basic-options.html#all-basic-scan-options
* License dashboard
  * License expressions
     Use --license CLI option for License expressions
     https://scancode-toolkit.readthedocs.io/en/stable/cli-reference/basic-options.html#all-basic-scan-options
  * License keys
     Use --license CLI option for License keys
     https://scancode-toolkit.readthedocs.io/en/stable/cli-reference/basic-options.html#all-basic-scan-options
  * License policy
     Use --license-policy CLI option for policy data
     https://scancode-toolkit.readthedocs.io/en/stable/plugins/licence_policy_plugin.html#using-the-plugin
* Package dashboard
  * Package types
     Use --package CLI option for package types
     https://scancode-toolkit.readthedocs.io/en/stable/cli-reference/basic-options.html#all-basic-scan-options
  * Package languages
     Use --package CLI option for package languages
     https://scancode-toolkit.readthedocs.io/en/stable/cli-reference/basic-options.html#all-basic-scan-options
  * Package licenses
     Use --package CLI option for package licenses
     https://scancode-toolkit.readthedocs.io/en/stable/cli-reference/basic-options.html#all-basic-scan-options

**Comment by OmkarPh** [comment]
@AyanSinhaMahapatra @pombredanne ^^

**Comment by OmkarPh** [comment]
Gentle reminder ^^

**Comment by AyanSinhaMahapatra** [comment]
@OmkarPh you can use these links (these don't exist yet as the PR above isn't merged and released):

copyright option: https://scancode-toolkit.readthedocs.io/cli-reference/basic-options.html#copyright-option
license option: https://scancode-toolkit.readthedocs.io/cli-reference/basic-options.html#license-option
package option: https://scancode-toolkit.readthedocs.io/cli-reference/basic-options.html#package-option
info option:  https://scancode-toolkit.readthedocs.io/cli-reference/basic-options.html#info-option

for license policy the link you posted is correct: https://scancode-toolkit.readthedocs.io/plugins/licence_policy_plugin.html#using-the-plugin

we can also use the stable link (docs from last tagged version).

Sorry for the delay!

**Comment by OmkarPh** [comment]
Thanks @AyanSinhaMahapatra ✌️

**Comment by OmkarPh** [comment]
> @OmkarPh you can use these links (these don't exist yet as the PR above isn't merged and released):
> 
> copyright option: https://scancode-toolkit.readthedocs.io/cli-reference/basic-options.html#copyright-option license option: https://scancode-toolkit.readthedocs.io/cli-reference/basic-options.html#license-option package option: https://scancode-toolkit.readthedocs.io/cli-reference/basic-options.html#package-option info option: https://scancode-toolkit.readthedocs.io/cli-reference/basic-options.html#info-option
> 
> for license policy the link you posted is correct: https://scancode-toolkit.readthedocs.io/plugins/licence_policy_plugin.html#using-the-plugin
> 
> we can also use the stable link (docs from last tagged version).
> 
> Sorry for the delay!

hi @AyanSinhaMahapatra 
these links still aren't working although PR is merged, is there any change needed in URL

**Comment by AyanSinhaMahapatra** [comment]
They also need to be released for this to work :P 

Note that: https://scancode-toolkit.readthedocs.io/en/latest/cli-reference/basic-options.html#copyright-option works but https://scancode-toolkit.readthedocs.io/en/stable/cli-reference/basic-options.html#copyright-option does not. 

Although we have released `scancode-toolkit`, there hasn't been any stable releases, only pre-release/release-candidates and maybe the stable doc build only happens from proper scancode releases.

You can use the `latest` doc version too here btw, no issues.

**Comment by OmkarPh** [comment]
oops, my bad

i'll update it to /en/latest then

**Comment by AyanSinhaMahapatra** [comment]
This has already been implemented and working. Thanks @OmkarPh, closing!
