### ISSUE TITLE
Empty directory displays file icon

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode-workbench#542]
### Description
In the Table View, empty directories display a file icon instead of a directory icon.

### System configuration
For bug reports, it really helps us to know:
* OS = Windows
* SCWB v4.0beta
* SCTK v31.1.1

**Comment by OmkarPh** [comment]
In the library, I couldn't find a way to explicitly specify if a node is file or directory, it just decides it on basis of whether it has children or not
I've asked about it here https://github.com/react-component/tree/issues/736

**Comment by mjherzog** [comment]
Good to know why. Lets hope they want to fix it.

**Comment by OmkarPh** [comment]
They've added a `isLeaf` API option to fix this
This fixes the issue, For future reference, sample scan - [withEmptyDir.json.txt](https://github.com/nexB/scancode-workbench/files/12782818/withEmptyDir.json.txt)
