### ISSUE TITLE
SCWB 4 does not display any License data for a Scan from SCTK 32

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode-workbench#548]
When we import Scans created with SCTK v32.0.0rc2 into SCWB 4.0-Beta there is no License data displayed. 
- The License data is clearly present in the JSON output for the Scan.
- The License Info View shows 0 Licenses and the Table View has no License data expect Unknown License = No for a file that has a detected license 
There was no error message from the Import/Conversion to SQLite.
It seems clear that this Issue is related to the re-organization of License data in SCTK v32.

**Comment by AyanSinhaMahapatra** [comment]
@mjherzog The https://github.com/OmkarPh/scancode-workbench/releases/tag/v4.0.0_beta4 release supports SCTK v31 AFAIK, but @omkar has already worked on supporting v32 (more work ongoing to add features, but it does support v32currently).

@OmkarPh I don't see the recent changes you showed in https://github.com/OmkarPh/scancode-workbench too, you should:

1. Push the changes here
2. Create a new release so we can try this out 

@pombredanne we also need a review from you at https://github.com/nexB/scancode-workbench/pull/532

**Comment by OmkarPh** [comment]
> @mjherzog The https://github.com/OmkarPh/scancode-workbench/releases/tag/v4.0.0_beta4 release supports SCTK v31 AFAIK, but @omkar has already worked on supporting v32 (more work ongoing to add features, but it does support v32currently).
> 

That's correct, I have not created a release binary for our recent changes, will do it this week


> @OmkarPh I don't see the recent changes you showed in https://github.com/OmkarPh/scancode-workbench too, you should:
> 
> 1. Push the changes here
> 2. Create a new release so we can try this out 
> 

@AyanSinhaMahapatra Yeah sure, my latest changes are in this branch, you can try running it in dev mode
https://github.com/OmkarPh/scancode-workbench/tree/schema/update_for_output_v3.0.0

**Comment by AyanSinhaMahapatra** [comment]
This is now supported in https://github.com/nexB/scancode-workbench/releases/tag/v4.0.0rc2,
and some bugs/issues are being tracked separately:
- #567 
- #565 
- #563 
- #562 
- #561 

Closing this!
