### ISSUE TITLE
Display scan file name in titlebar

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode-workbench#549]
We need do display the name of the current Scan file somewhere that is visible at all times, probably in the title bar like Excel. This is very important when you are using multiple SCWB instances.

**Comment by OmkarPh** [comment]
Default:
![image](https://user-images.githubusercontent.com/48476025/229187802-dbc64316-785c-4542-9c71-99f88a3ea574.png)

On import
![image](https://user-images.githubusercontent.com/48476025/229187869-d2e12625-550f-47f8-a14c-5d94ff51e267.png)
![image](https://user-images.githubusercontent.com/48476025/229188135-d333df7c-0500-4e1d-bc06-f539db9f721f.png)

**Comment by johnmhoran** [comment]
Very nice @OmkarPh .  👍

**Comment by mjherzog** [comment]
This is what we are looking for. I We will need to decide what to do when the SCWB window size does not have enough room for the full name.  I am not sure what the best practice is, but Excel truncates the name right to left so that may be a good approach.

**Comment by OmkarPh** [comment]
Also, I'm creating provision for handling multiple windows (IPC isn't managed correctly for this right now, and there's no option to create new window either)

File>New Window or Ctrl+N  this would be ideal way ig

**Comment by mjherzog** [comment]
With v4.0.0rc2 the filename is nicely displayed, but when I open a new SQLITE file in the same session the filename is not refreshed.

**Comment by OmkarPh** [comment]
Note - There's a bug in this titlebar feature.
if you import a large scan, and shift to another application while its processing & then come back after the import is completed, the titlebar isn't updated (It's because focused window is different at the point when scan is complete)

I am working on it

**Comment by mjherzog** [comment]
Thanks. I thought that I had seen this bug, but I could not reproduce it with smaller Scan files.

**Comment by OmkarPh** [comment]
This issue has been fixed in #560 and available at https://github.com/nexB/scancode-workbench/releases/tag/v4.0.0rc3
it updates the title bar correctly regardless of whether the window is focused or not
