### ISSUE TITLE
Save column order for Custom Columns

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode-workbench#550]
When you customize the columns during a session, SCWB retains the column set when you import a different JSON file or open a different SQLITE file, but it does not retain the column order. It reverts to the default column order from the Custom Columns modal window. 
SCWB should retain the column order during a work session.

**Comment by OmkarPh** [comment]
working on it

**Comment by OmkarPh** [comment]
This is implemented in #568

**Comment by OmkarPh** [comment]
we can close this, as it's fixed & available at https://github.com/nexB/scancode-workbench/releases/tag/v4.0.0rc3
