### ISSUE TITLE
Filters in file view are not for selected directory

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [aboutcode-org/scancode-workbench#551]
### Description
Scan result used: 
[hazelcast-3293.json.txt](https://github.com/nexB/scancode-workbench/files/11093528/hazelcast-3293.json.txt)

![workbench-filter-bug](https://user-images.githubusercontent.com/25746274/228348181-97ed4d64-7195-4e79-bf93-cf0738f5e43f.png)

Notice how there are only files with `.java` extension under the selected directory but in the extension drop down filter, the options are not from just this directory but from all directories together. This drop down filter should be selective and only from the directory which is selected on the left.

### System configuration

* What OS are you running on? (Windows/MacOS/Linux) Linux
* What version of scancode-workbench are you running on? dev build on https://github.com/OmkarPh/scancode-workbench/tree/schema/update_for_output_v3.0.0
* What version of scancode-toolkit was used to generate the scan file? v32.0.0rc3

**Comment by OmkarPh** [comment]
working on it

**Comment by OmkarPh** [comment]
Hey @AyanSinhaMahapatra , this is fixed in current version

**Comment by AyanSinhaMahapatra** [comment]
@omkar yes! 
See following example for the same scan reported above, and this time we have correct options in the filters:
![workbench-filters-fixed](https://user-images.githubusercontent.com/25746274/233102901-4ff4327b-5215-48b1-95da-745e0281972b.png)
