### ISSUE TITLE
Filter "box" display is erratic for long lines

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode-workbench#554]
When you open the filter list box for some fields you get a blank list or erratic data. The modal window usually displays beyond the width of SCWB. This is common with Copyright data and was also a bug in SCWB v3.

**Comment by OmkarPh** [comment]
will trim the text to a preset max size, with ellipsis

**Comment by OmkarPh** [comment]
Closing, as this was fixed in the PR mentioned
