### ISSUE TITLE
License detection displays 'No License Detection to show' but shows data when selected

### ISSUE THREAD

**Issue by johnmhoran** [aboutcode-org/scancode-workbench#564]
Reviewing `pkg:maven/com.google.auth/google-auth-library-credentials@0.24.1?type=src`, we have 1 row with 3 `bsd-new` detections.  Before I select that row with my mouse, the right-hand area shows `No License Detection to show`, but when I select that row on the left, I see 3 rows of `bsd-new` details (score/match coverage = 100).

![image](https://user-images.githubusercontent.com/11096678/234113781-b78fabc9-510a-45f6-aec3-020320839bed.png)

![image](https://user-images.githubusercontent.com/11096678/234113916-9871d9e7-2e3d-4faf-ac23-5f6a410daccc.png)

**Comment by AyanSinhaMahapatra** [comment]
We should have the first one selected as we enter the view (we do this in packages view too)

**Comment by OmkarPh** [comment]
> We should have the first one selected as we enter the view (we do this in packages view too)

yep, my bad
will fix this soon

**Comment by OmkarPh** [comment]
we can close this, as it's fixed & available at https://github.com/nexB/scancode-workbench/releases/tag/v4.0.0rc3
