### ISSUE TITLE
Also show license clues

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [aboutcode-org/scancode-workbench#565]
### Description

We don't show `resource.license_clues` currently but this is required too in the license detections explorer.

Consider the following scan:
[bcpg-fips-1.0.4.jar-v32rc4results.json.txt](https://github.com/nexB/scancode-workbench/files/11337035/bcpg-fips-1.0.4.jar-v32rc4results.json.txt)

There is a license clue detection at `bcpg-fips-1.0.4.jar-extract/META-INF/BC2048KE.DSA`

like this:

```
"detected_license_expression": null,
      "detected_license_expression_spdx": null,
      "license_detections": [],
      "license_clues": [
        {
          "score": 8.93,
          "start_line": 43,
          "end_line": 43,
          "matched_length": 5,
          "match_coverage": 8.93,
          "matcher": "3-seq",
          "license_expression": "ipa-font",
          "rule_identifier": "ipa-font_5.RULE",
          "rule_relevance": 100,
          "rule_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/ipa-font_5.RULE",
          "matched_text": "constitutes acceptance of the [DigiCert] [CP]/[CPS] [and] [the] [Relying] [Party] Agreement"
        }
```

This should be displayed similar to how other dependencies are shown in package explorer, they are in another section down below, but looks exactly like the other license detections. I.e.

there would be one entry on the left for each license match, and one entry in the license match table in the right, and the file region in the corresponding table.

**Comment by OmkarPh** [comment]
Closing, as license clues are added to the license explorer
