### ISSUE TITLE
Don't show `other dependencies` in package explorer when empty

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [aboutcode-org/scancode-workbench#566]
### Description

We should not show anything here, just a blank screen with `No packages/dependencies detected` like we do in license detections explorer. (Both of these empty view needs to be a bit more polished as a refinement, in the center of the screen at least and not plain text)

Consider the following scan:
[bcpg-fips-1.0.4.jar-v32rc4results.json.txt](https://github.com/nexB/scancode-workbench/files/11337035/bcpg-fips-1.0.4.jar-v32rc4results.json.txt)
![workbench-empty-packages](https://user-images.githubusercontent.com/25746274/234699325-08c1eef6-4300-44d6-9f30-44fc6399c4e7.png)

**Comment by OmkarPh** [comment]
we can close this, as it's fixed & available at https://github.com/nexB/scancode-workbench/releases/tag/v4.0.0rc3
