### ISSUE TITLE
Improve search for license expressions in License Detections Explorer dashboard

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode-workbench#574]
I am running SCWB v4.0.0.rc3 on Windows.

When you access the License Detections Explorer dashboard there is no obvious order for the list of license-expressions. It is definitely not alpha order or number of detections. This should be an alpha order default so at least you can intelligently scroll to find what you are looking for. It would be even better to have a search option for the list.

This improvement would be generally very useful and there is the more specific use case where you are looking for a pattern in a license detection that applies to multiple files.

**Comment by mjherzog** [comment]
@johnmhoran I assigned to you for review of the problem/solution statement

**Comment by johnmhoran** [comment]
Thanks @mjherzog .  This looks good.  Alpha order would also make it easier for the user to keep track of his or her review progress.

**Comment by OmkarPh** [comment]
what do we exactly mean by 'alpha order' here?

**Comment by mjherzog** [comment]
I mean alphabetic order for the license expression so apache-2.0 before gpl-2.0. I was guessing that we could treat the license expression as a string and use that to sort in alphabetic order.

**Comment by OmkarPh** [comment]
got it

**Comment by AyanSinhaMahapatra** [comment]
Note that the alphabetical sorting order is also being implemented directly at scancode-toolkit top level license detections at: https://github.com/nexB/scancode-toolkit/pull/3430/commits/37067440fb07827e02ac090f2efd684c3530f0c3 as it made more sense there too (and this will be propagated elsewhere too). So this need not be implemented again here in SCWB.

> It would be even better to have a search option for the list.

Keeping the issue open for this part ^

**Comment by OmkarPh** [comment]
Fixed a Bug in latest commit - Letter cases weren't handled correctly, For example searching for `or` didn't display entries with `OR`
