### ISSUE TITLE
Fix description for License_detections column in Custom Columns window

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode-workbench#576]
I am using SCWB v4.0.0.rc3 on Windows.

When you select Custom Columns there is a checkbox with no description below "License text %".  If you check that box, the column header in the Table View is "License_detections" which links to the License Detections Explorer. The bug is the missing description in the Custom Columns window.

**Comment by OmkarPh** [comment]
Thank you for reporting
I've added a fix in the existing PR

**Comment by AyanSinhaMahapatra** [comment]
Thanks @OmkarPh , this is fixed in the PR!
