### ISSUE TITLE
Add Copyright Dashboard

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode-workbench#578]
Copyrights are a first-class data element for provenance analysis. We currently have two Copyright items on the File Info Dashboard:
- Unique Copyright Holders Detected: number
- Copyright Holders: pie chart

We need to add:
- Unique Copyright Notices Detected: number
- Copyright Notices: pie chart
- 
and we could also add:
- Unique Authors Detected: number
- Authors: pie chart

The Copyright/Author data is available in the Chart Summary View, but pretty hard to use particularly when there is a large number for "No Value detected".

On the File Info we should replace the Copyright Holder pie char with Mime types and keep just the Directories and Files numbers in the top section.

**Comment by OmkarPh** [comment]
Closing, as it is implemented & merged
