### ISSUE TITLE
Add Dependencies Dashboard

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode-workbench#579]
This is a placeholder for a new Dependencies Dashboard. We can emulate the SCIO UI which currently shows pie charts for:
- Package Type (number of dependencies of each package type)
- Runtime Dependencies (out of all dependencies is_runtime: True or False)
- Resolved Dependencies (out of all dependencies is_resolved: True or False)
- Optional Dependencies (out of all dependencies is_optional: True or False)

**Comment by AyanSinhaMahapatra** [comment]
@OmkarPh This would be a dependency info dashboard ^ similar to the package info dashboard.

We can have the 4 pie charts @mjherzog referenced above, I've added some minor details there.

Btw also putting a improvement we thought about here:
In the packages explorer:

* Filtering by Runtime/Optional/Resolved dependencies
* Using icons to show this data for each dependency in the left pane (same icon without the text, what we have on the right dependencies details)
* Using a non-white background for the `optional` icon.

Just food for thought ^ 

Also in the top bar `View` we might want to have all the views like these too maybe?

**Comment by AyanSinhaMahapatra** [comment]
Note that this is addressed by the PR above ^

But there was more UI suggestions in the community calls which is being experimented with in this branch: https://github.com/nexB/scancode-workbench/tree/experiment/dependenciesViews

**Comment by OmkarPh** [comment]
Closing this, as the community suggestions are tracked in #588
