### ISSUE TITLE
Add numbers to % for all pie charts

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode-workbench#581]
In the SCIO pie charts you can get the number of items in addition to the percentage when you mouse over a pie chart segment.
We need the same feature for the SCWB pie charts.

**Comment by OmkarPh** [comment]
Something like this ?
![image](https://github.com/nexB/scancode-workbench/assets/48476025/6ef211d7-1d21-4889-99e7-5dccf0c44c73)

**Comment by AyanSinhaMahapatra** [comment]
@OmkarPh Yes! I've tried this from your branch above and this works.
One minor thing: notice the tooltip going outside the window at the right
![tooltip-outside](https://github.com/nexB/scancode-workbench/assets/25746274/6bb4eecb-5410-4a4f-bcc1-3a364314becf)

**Comment by OmkarPh** [comment]
> One minor thing: notice the tooltip going outside the window at the right 

This is the limitation of c3 charts, This is out of scope for now
