### ISSUE TITLE
Update docs on CentOS installation

### ISSUE THREAD

**Issue by meizq** [aboutcode-org/scancode-workbench#592]
### Description
This problem has been puzzling me for several days.I downloaded the application on CentOS and it opens the interface, but it seems to not be working properly. For example, when I click the "import json file" button, nothing happens. I have already checked for any permission issues and node version . I want to know if the application is indeed not supported to run on CentOS7，or if someone has successfully run it on CentOS 7. Are there any modifications that need to be made?

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? (Linux)
* What version of scancode-workbench are you running on?：3.1.1
* What version of scancode-toolkit was used to generate the scan file?3.1.1

**Comment by AyanSinhaMahapatra** [comment]
@meizq Thanks for the report!
 I have not tested this for CentOS, but I was able to run the v3.1.1 on Ubuntu 20 allright.
I installed the scancode-toolkit v3.1.1 from: https://github.com/nexB/scancode-workbench/releases/tag/v3.1.1
and after `./configure` and `scancode -clipeu samples/ --json-pp samples.json --classify --summary`, I loaded the samples.json in scancode workbench https://github.com/nexB/scancode-workbench/releases/tag/v3.1.1 without any issues (This version has other known bugs though, and is deprecated in favor of newer versions).

Can you go to `View` -> `Toggle Developer Tools` and see if there's any Error there?

Note that both these versions are from september 2017 and we have had multiple major releases of SCTK and a complete re-write of scancode-workbench by @OmkarPh  with lots of new features and update in these 4 years.
Could you test the following versions of SCWB and SCTK on CentOS also and report whether these work allright?

- https://github.com/nexB/scancode-toolkit/releases/tag/v32.0.6
- https://github.com/nexB/scancode-workbench/releases/tag/v4.0.0rc4

These should be supported allright on CentOS (https://scancode-toolkit.readthedocs.io/en/stable/getting-started/install.html#system-requirements) but we don't have tests on CentOS currently. This is tracked at https://github.com/nexB/scancode-toolkit/issues/2731

**Comment by meizq** [comment]
Hello, I ran Workbench4 on CentOS 7, and below is the result of the execution.
It seems there are two main issues: one is the lack of support for the underlying lib, and the other is an error related to GPU.
<img width="892" alt="scancode" src="https://github.com/nexB/scancode-workbench/assets/26680434/021b950e-0e61-409a-b1ef-f7cb215bbfbc">

**Comment by AyanSinhaMahapatra** [comment]
@meizq thanks for testing this out and reporting!

This seems like a issue faced by others too in same/other contexts. Could you check out solutions in https://stackoverflow.com/questions/20357033/usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxxabi-1-3-8-not-found and see if this works? We can add docs related to this issue specifically if any of this fixes the issue.
Also check out https://jdhao.github.io/2017/09/04/install-gcc-newer-version-on-centos/ which comes up in some of the forum posts in stackoverflow to solve this issue.

Also btw, pasting the output directly is always better than screenshots :wink:

**Comment by meizq** [comment]
There is good news. I manually installed the new libstdc++ , and changed LD_LIBRARY_PATH in console(I do not have permission to directly modify /usr/lib64 dir). After that, the workbench finally runs normally on centos7!
In summary, I think there are two main points. Firstly, using the * new libstdc++** library on CentOS 7. Secondly, when running, it needs to be added with ** --no-sandbox** option. 
 I am very grateful for your patient explanations.

**Comment by meizq** [comment]
There is good news. I manually installed the new libstdc++ ,and changed LD_LIBRARY_PATH in console(I do not have permission to directly modify /usr/lib64.).After that, the workbench finally runs normally on centos7!
In summary, I think there are two main points. Firstly, using the **new libstdc++** library on CentOS 7. Secondly, when running, it needs to be added with **--no-sandbox** option.
 I am very grateful for your patient explanations.

**Comment by AyanSinhaMahapatra** [comment]
@meizq thanks for the update! If you have more feedback on workbench, please let us know at https://matrix.to/#/#aboutcode-org_scancode-workbench:gitter.im and/or open issues.

@OmkarPh note ^ that we might want to add [this](https://github.com/nexB/scancode-workbench/issues/592#issuecomment-1659938174) to the docs at some point. Keeping this issue open for now.

**Comment by OmkarPh** [comment]
> There is good news. I manually installed the new libstdc++ ,and changed LD_LIBRARY_PATH in console(I do not have permission to directly modify /usr/lib64.).After that, the workbench finally runs normally on centos7! In summary, I think there are two main points. Firstly, using the **new libstdc++** library on CentOS 7. Secondly, when running, it needs to be added with **--no-sandbox** option. I am very grateful for your patient explanations.

Thanks @meizq for the update !

**Comment by OmkarPh** [comment]
> @meizq thanks for testing this out and reporting!
> 
> This seems like a issue faced by others too in same/other contexts. Could you check out solutions in https://stackoverflow.com/questions/20357033/usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxxabi-1-3-8-not-found and see if this works? We can add docs related to this issue specifically if any of this fixes the issue. Also check out https://jdhao.github.io/2017/09/04/install-gcc-newer-version-on-centos/ which comes up in some of the forum posts in stackoverflow to solve this issue.
> 
> Also btw, pasting the output directly is always better than screenshots 😉

Thanks @AyanSinhaMahapatra for the quick response 🚀

**Comment by OmkarPh** [comment]
This same issue is mentioned in the sqlite3 repository also - https://github.com/TryGhost/node-sqlite3/issues/1582#issuecomment-1198949710

**Comment by OmkarPh** [comment]
hi @meizq 
I'm adding this to the docs
If possible, Can you share the exact commands you used to install the libstdc++ and run the app?

**Comment by OmkarPh** [comment]
I've updated the docs
You can find it here https://github.com/nexB/scancode-workbench/blob/update/docs/docs/source/contribute/building.rst#linux

**Comment by OmkarPh** [comment]
Closing as it is implemented and available in [v4.0.0 Release](https://github.com/nexB/scancode-workbench/releases/tag/v4.0.0)
