### ISSUE TITLE
right-click in table view does not provide menu selection

### ISSUE THREAD

**Issue by dusty-schafer** [aboutcode-org/scancode-workbench#595]
I've scanned u-boot sources and zlib.  In both cases, the .json and .sqlite files can be opened and saved respectively.
In the Table View, right-click on a node or file does not respond.  There's no menu item to select.  Nothing happens.
In Workbench v3.1.1, with the same .sqlite file, the right-click opens the menu with "Edit Conclusion".  And selecting the "Edit Conclusion" the dialog box opens and works properly.

Thanks for the support!

### System configuration
Windows 10  Build: 19042.2965
Version of scancode-workbench: v4.0.0rc4
ScanCode version: 32.0.6
ScanCode Output Format version: 3.0.0
SPDX License list version: 3.21

**Comment by mjherzog** [comment]
@dusty-schafer The Conclusions feature was deprecated for v4.0. It was a complex feature to maintain for limited functionality in a single-user/desktop tool. We have focused our development on improving and adding views for the Scan data.
In the long term we expect to add some similar functionality in ScanCode.io.

**Comment by dusty-schafer** [comment]
Ah, okay, makes sense.  Thanks for reaching out.
BTW – the new views, especially the “license explorer” is fantastic!  Nice going!  😉

dusty
