### ISSUE TITLE
Add File / Close command

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode-workbench#596]
### Description
We should add a Close command to the File menu. This command would clear the current Scan data and return you to the Home screen. 
This would address a current problem for the use case:
- You have a medium to large Scan open in SCWB
- You want to switch to viewing another Scan by opening a SQLite file or importing a JSON file
- The SCWB display retains the old data in the Table View until after the new file is fully processed which is confusing
- Also it seems to take much longer to load a new Scan than to close SCWB and start over

This has been a long-standing problem and it is still present for v4.0.0r3. I will retest with v40.0rc4

**Comment by mjherzog** [comment]
I just tested on v4.0.0rc4 and the new Scan loaded much more quickly than v4.0.0rc3. It still might be a good idea to provide an explicit File Close command.

**Comment by OmkarPh** [comment]
> * The SCWB display retains the old data in the Table View until after the new file is fully processed which is confusing

Yep, this needs to be resolved 

In addition to the menu item (with a shortcut), we should flush the previous scan immediately when the new scan is parsed successfully (If unsuccessful, then keeping the old scan is ok IMO)

**Comment by mjherzog** [comment]
I suggest the Close command should flush the previous scan immediately - no reason to wait on the results of parsing the new scan. This should be much simpler and the user can always re-open the prior scan if that is what they want to do

**Comment by AyanSinhaMahapatra** [comment]
> I suggest the Close command should flush the previous scan immediately - no reason to wait on the results of parsing the new scan.

Yeah this would be better (unsuccessful parsing should be rare anyway)

**Comment by OmkarPh** [comment]
what would be an ideal keyboard shortcut for close command?
I thought of `Ctrl+w` but it's already being used to close the window

**Comment by mjherzog** [comment]
perhaps Ctrl+c

**Comment by OmkarPh** [comment]
> perhaps Ctrl+c 

That's reserved for copying :)

**Comment by OmkarPh** [comment]
Closing as it is implemented and available in [v4.0.0 Release](https://github.com/nexB/scancode-workbench/releases/tag/v4.0.0)
