### ISSUE TITLE
Fit table height & column widths to requirement

### ISSUE THREAD

**Issue by OmkarPh** [aboutcode-org/scancode-workbench#598]
### Description
Sometimes the table has only a few rows but takes up a lot more space than necessary.
Similarly, the column width setup sometimes leads to waste of screen area, when other columns need more space.
The table width & height can be optimised by taking these things into account

Carried forward from #594

**Comment by divyanshu255** [comment]
i want to work on this,please assign

**Comment by OmkarPh** [comment]
sure, go ahead 🚀 
Checkout from this branch [feature/unittests](https://github.com/nexB/scancode-workbench/tree/feature/unittests)

**Comment by OmkarPh** [comment]
gentle ping @divyanshu255 
Any update on this ?

**Comment by OmkarPh** [comment]
Hey @divyanshu255 
I've fixed this issue as there was no response, and we're in the process of preparing for our next release

Feel free to take up another issue

**Comment by OmkarPh** [comment]
Closing as it is implemented and available in [v4.0.0 Release](https://github.com/nexB/scancode-workbench/releases/tag/v4.0.0)
