### ISSUE TITLE
Change color of SCWB icon

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode-workbench#603]
The black SCWB icon is very hard to see in a Windows tray and presumably also on other platforms. We need to change the color from black to something more colorful - blue or orange or possibly orange for the outline and blue for the inside.

**Comment by OmkarPh** [comment]
Some options:
1.
![output-onlinepngtools (2)](https://github.com/nexB/scancode-workbench/assets/48476025/7e7e9562-dd53-45de-b934-90e86631a4e9)
2.
![output-onlinepngtools (4)](https://github.com/nexB/scancode-workbench/assets/48476025/23b61c3a-8a78-49a6-8906-dbbc0dd52877)
3.
![output-onlinepngtools (5)](https://github.com/nexB/scancode-workbench/assets/48476025/bc0434e0-ef21-43fd-915d-2ad876e6ae0a)
4.
![output-onlinepngtools (6)](https://github.com/nexB/scancode-workbench/assets/48476025/74986189-5ab0-43f7-83a3-0949c5b0c4f8)

**Comment by mjherzog** [comment]
I think that option 1 is best for general visibility. Could we change the bars inside the outline to orange to make the icon more distinctive?

**Comment by OmkarPh** [comment]
I've created a design file - 

https://www.figma.com/file/sRqMGSKQIarcdwa6KYFcpc/Workbench-Icon?type=design&node-id=0%3A1&mode=design&t=V13wEpH8AdPF4Zah-1

**Comment by mjherzog** [comment]
@OmkarPh thank you for drafting some other options. I think that 8 or 1 will be most distinctive as an icon.
@DennisClark @pombredanne Do you have any input

**Comment by OmkarPh** [comment]
Closing as it is updated in [v4.0.0 Release](https://github.com/nexB/scancode-workbench/releases/tag/v4.0.0)
