### ISSUE TITLE
ScanCode Workbench is damaged and can't be opened on Mac M2

### ISSUE THREAD

**Issue by mattwhetton** [aboutcode-org/scancode-workbench#605]
### Description
I just downloaded ScanCode Workbench (macos-arm64), unzipped it and tried to open it but get the following error:

`“ScanCode Workbench” is damaged and can’t be opened. You should move it to the Bin.`

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? Mac OS M2
* What version of scancode-workbench are you running on?  4.0.0

**Comment by OmkarPh** [comment]
It was built on my M1 air and should ideally work on any apple-silicon machine
Can you try this once - https://drive.google.com/file/d/1wcH_bKnSNbWWeUpPrg2QlUZKdlKRb9wY/view?usp=sharing

**Comment by mattwhetton** [comment]
I have the same problem with this one too

**Comment by OmkarPh** [comment]
I came across this thread https://discussions.apple.com/thread/253714860?answerId=257037956022#257037956022

Seems like the application is flagged `Quarantine` as it's downloaded from sources other than the app store.

**Comment by mattwhetton** [comment]
That looks like its solved it - what a confusing message! Thank you

**Comment by OmkarPh** [comment]
> That looks like its solved it - what a confusing message! Thank you

yeah,
still this is a workaround, we'll have to see if there's something we can do while packaging itself
