### ISSUE TITLE
Improve View Navigation

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [aboutcode-org/scancode-workbench#612]
There are two more improvements that is possible in view navigation:

1. In Package explorer, we can have a section for license detections in that package (with links to the specific items in the License Explorer) This can be simple list just like the Data File paths in Package Explorer
2. In License Explorer, the file regions in the File region section has two types of origins, file and package, as shown by icons. Presently for both these cases we go to the respective file in table view. Would it be better to go to the respective package in this case in the Package explorer when the Detection origin is a package? This is a RFC

**Comment by OmkarPh** [comment]
hi @AyanSinhaMahapatra 
I've fixed the first part of this in #610 
For the second part, let's discuss more in the weekly call

**Comment by OmkarPh** [comment]
For  navigation from license explorer > File regions to Packages,
how about having link on the icon itself:
![image](https://github.com/nexB/scancode-workbench/assets/48476025/cbfa2edd-41e0-4668-96ec-f75d664f6c7c)

**Comment by AyanSinhaMahapatra** [comment]
@OmkarPh 

> how about having link on the icon itself:

Yeah, this makes sense. :+1:

**Comment by OmkarPh** [comment]
Closing, as both the suggestions are implemented and merged
